### ISSUE TITLE
Recurse into nested and embedded structs automatically

### ISSUE THREAD

**Issue by ansel1** [creasty/defaults#1]
I seems that you need to tag struct fields with `default:"{}"` to recurse into them.  Should this be the default, even with no "default" tag?  You can opt out with `default:"-"`.  That follows the conventions of most packages which do similar tag-based stuff.

So, for example:

    type DBConfig struct {
      URL string `default:"pg://localhost:5432/db"`
    }

    type Config struct {
      DBConfig
    }

    var cfg Config
    defaults.Set(&cfg)

That should recurse into the embedded DBConfig.

**Comment by creasty** [comment]
Thanks for the report. I've fixed it.
