### ISSUE TITLE
Default value to the entry that key already exists in a map

### ISSUE THREAD

**Issue by nakabonne** [creasty/defaults#28]
Hi, thank you for making and maintaining such an amazing package. It helps me a lot!

I'm facing an issue that is not able to set default values within a `map[string]struct{}`. I'd like to set the default value to the entry that key already exists in a map. But it doesn't work well:

```go
package main

import (
	"fmt"

	"github.com/creasty/defaults"
)

type T struct {
	Field string `default:"value-1"`
}

type Foo struct {
	Map map[string]T
	T   T
}

func main() {
	f := &Foo{
		Map: map[string]T{
			// I want to set the default value here.
			"key-1": T{},
		},
	}
	if err := defaults.Set(f); err != nil {
		panic(err)
	}
	fmt.Printf("field in map: %q\n", f.Map["key-1"].Field)
	fmt.Printf("field in struct: %q\n", f.T.Field)

	// Output:
	//
	// field in map: ""
	// field in struct: "value-1"
}
```

Currently, I workaround like:

```go
	for k, v := range f.Map {
		_ = defaults.Set(&v)
		f.Map[k] = v
	}
```

Is there another way to set a default value for a value that already has a key in the map?

Thanks!

**Comment by creasty** [comment]
We'll need logic similar to this:

https://github.com/creasty/defaults/blob/369aea68802adf9a80a605a76be421836a9961bf/defaults.go#L165-L170

**Comment by nakabonne** [comment]
That makes sense. It seems to be a good first issue.

**Comment by zenthangplus** [comment]
@creasty @nakabonne I've created a MR for this issue https://github.com/creasty/defaults/issues/28

**Comment by nakabonne** [comment]
Nice 👍

**Comment by creasty** [comment]
Fixed in https://github.com/creasty/defaults/releases/tag/v1.6.0
