### ISSUE TITLE
Booleans and defaults seems not to be working

### ISSUE THREAD

**Issue by datencia** [creasty/defaults#30]
Hi, I'm trying to use this library but I'm facing an issue setting defaults values for a boolean field

In my example, I am setting a boolean default value to `true` for the `Enabled` field but when passing a `false` value it turns to `true`

```
package main

import (
	"fmt"
	"github.com/creasty/defaults"
)

type Sample struct {
	Enabled bool `default:"true"`
}

func main() {
	obj := &Sample{Enabled: false}
	if err := defaults.Set(obj); err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", obj)
}
```

Output: `&{Enabled:true}`

am I missing something?

Here is a playground where you can test it: https://play.golang.org/p/RIeiduC2c8C

**Comment by creasty** [comment]
In Golang, `&Sample{Enabled: false}` is equivalent to `&Sample{}`.
Hence whether or not you explicitly set `false` is indistinguishable. The same goes for `0` of numeric types and `""` (an empty string) of string.

You could use a pointer to bool (`*bool`) or a wrapped type such as https://github.com/guregu/null.

**Comment by zhaoyunxing92** [comment]
I was wondering if we could handle it this way

``` go
func isInitialValue(field reflect.Value) bool {
	switch field.Kind() {
	case reflect.Bool:
		return field.Interface() != false
	case reflect.Int:
		return field.Interface() != 0
	default:
		return reflect.DeepEqual(reflect.Zero(field.Type()).Interface(), field.Interface())
	}
}
```
