### ISSUE TITLE
Unable to keep zero value in case of setting the zero value on purpose

### ISSUE THREAD

**Issue by khanhtc1202** [creasty/defaults#31]
Hi @creasty, thanks for the excellent package. I faced a typical case but am unsure how to use your package to address that.

In the case of the field of type bool, the go default bool value is `false` - boolean zero value. If I want to set the default value to `true` with your defaults package, it works as expected in case no value was set to that field. If the value for that field is set to zero value on purpose (bool zero is `false`), the `defaults.Set()` always override that field value with the configured value regardless of the original value.

```go
package main

import (
	"fmt"
	"github.com/creasty/defaults"
)

type Sample struct {
	Hello  string `default:"world"` // Tags in a nested struct also work
	Foo    int    `default:"-"`
	Random int    `default:"-"`
	Bool   bool   `default:"true"`
}

func main() {
	obj := &Sample{Hello: "hello", Bool: false}
	if err := defaults.Set(obj); err != nil {
		panic(err)
	}
	fmt.Println(obj)
}
```

I tried with `defaults.CanUpdate(obj.Bool)` too, but it looks like it checks for the zero value of type and compares with the current set value, which is already a zero value, hence not have any meaning here since the set value is zero value.

In case of check with `defaults.CanUpdate(obj)`, all the values will not be set since `obj.Hello` is not zero value of string, and that cause `obj.Bool` will not be set to `true` in case it's not yet set.

play: https://play.golang.org/p/5LoqUH5d1wj

**Comment by creasty** [comment]
Please refer to https://github.com/creasty/defaults/issues/30#issuecomment-942435138

**Comment by khanhtc1202** [comment]
I see, my miss on checking closed issues; thanks for your quick response 👍
